const fonts = {
  family: {
    black: 'Pretendard-Black',
    bold: 'Pretendard-Bold',
    extrabold: 'Pretendard-ExtraBold',
    extralight: 'Pretendard-ExtraLight',
    light: 'Pretendard-Light',
    medium: 'Pretendard-Medium',
    regular: 'Pretendard-Regular',
    semibold: 'Pretendard-SemiBold',
    thin: 'Pretendard-Thin',
    poppinsBlack: 'Poppins-Black',
    poppinsBold: 'Poppins-Bold',
    poppinsExtrabold: 'Poppins-ExtraBold',
    poppinsExtralight: 'Poppins-ExtraLight',
    poppinsLight: 'Poppins-Light',
    poppinsMedium: 'Poppins-Medium',
    poppinsRegular: 'Poppins-Regular',
    poppinsSemibold: 'Poppins-SemiBold',
    poppinsThin: 'Poppins-Thin',
  },
  size: {
    '4XS': 11,
    '3XS': 12,
    '2XS': 13,
    XS: 14,
    SM: 15,
    MD: 16,
    LG: 17,
    XL: 18,
    '2XL': 20,
    '3XL': 24,
    '4XL': 28,
    '5XL': 32,
    '6XL': 36,
  },
  lineHeight: {
    '4XS': 16,
    '3XS': 18,
    '2XS': 18,
    XS: 20,
    SM: 22,
    MD: 22,
    LG: 24,
    XL: 24,
    '2XL': 28,
    '3XL': 36,
    '4XL': 40,
    '5XL': 44,
    '6XL': 48,
  },
  letterSpacing: {
    none: 0,
  },
};

export { fonts };
