const semanticString = {
  effectType: {
    overdrive: '오버드라이브',
    distortion: '디스토션',
    fuzz: '퍼즈',
    boost: '부스터',
    chorus: '코러스',
    flanger: '플랜저',
    phaser: '페이저',
    tremolo: '트레몰로',
    vibrato: '비브라토',
    rotarySpeaker: '로터리 스피커',
    delay: '딜레이',
    reverb: '리버브',
    compressor: '컴프레서',
    sustainer: '서스테이너',
    limiter: '리미터',
    noiseGate: '노이즈 게이트',
    equalizer: '이퀄라이저',
    wah: '와우',
    envelopeFilter: '엔벨롭 필터',
    preamp: '프리앰프',
    pitchShifter: '피치 쉬프터',
    octaver: '옥타버',
    harmonizer: '하모나이저',
    tuner: '튜너',
    looper: '루퍼',
    volumePedal: '볼륨 페달',
    expressionPedal: '익스프레션 페달',
    switcher: '스위처',
    simulator: '시뮬레이터',
    multiEffects: '멀티이펙터',
    ringModulator: '링 모듈레이터',
    talkbox: '토크박스',
    signalBuffer: '시그널 버퍼',
    powerSupply: '파워 서플라이',
    pedalboard: '페달보드',
    patchCable: '패치케이블',
  },
  condition: {
    brandNew: '신품',
    mint: '매우 양호',
    good: '양호',
    fair: '보통',
    poor: '하자/고장',
  },
  time: {
    justNow: '방금 전',
    minuteAgo: '분 전',
    hourAgo: '시간 전',
    dayAgo: '일 전',
  },
  string: {
    searchPlaceholder: '어떤 악기를 찾고 있나요?',
  },
};

export { semanticString };
